### ISSUE TITLE
Temp is 0 for AMD k10temp

### ISSUE THREAD

**Issue by ferrreo** [ssleert/zfxtop#2]
As above, it's reading 0 for AMD for temps.

I can read the temp myself at: /sys/class/hwmon/hwmon6/temp1_input

I think line 292 of depend.go needs to be something like

`if string(f) == "coretemp\n" || string(f) == "k10temp\n" {`

Though after taking a second look I don't think the averaging code is correct as k10temp provides temps for each CCD as well as the hotspot temp so averaging them isn't correct. Should just take the hotspot (Tctl in the _label file).

![image](https://user-images.githubusercontent.com/482133/221420478-77c7113d-5dcb-4a8d-8f9d-1e02a53fca26.png)

**Comment by ssleert** [comment]
I'll fix it tomorrow.

**Comment by ferrreo** [comment]
Created a PR https://github.com/ssleert/zfxtop/pull/14 to fix the temp values being averaged incorrectly

**Comment by Lucas-101** [comment]
Close?
