### ISSUE TITLE
[Feature request] Option for RGB colors

### ISSUE THREAD

**Issue by Oman395** [ssleert/zfxtop#5]
Hey, this looks incredible! I'd love to be able to use rgb colors so I can catppuccinify it. Thanks!

**Comment by ssleert** [comment]
no
or contribute

**Comment by amytimed** [comment]
bruh

**Comment by ssleert** [comment]
> bruh

i am too lazy to do this
and dont need it

**Comment by amytimed** [comment]
most professional maintainer of all time

**Comment by Oman395** [comment]
Hey, only reason I'm professional in the repos I maintain is because it's part of an org-- he's honest, I respect it

**Comment by amytimed** [comment]
> Hey, only reason I'm professional in the repos I maintain is because it's part of an org-- he's honest, I respect it

true
