### ISSUE TITLE
No icons

### ISSUE THREAD

**Issue by Capitalmind** [ssleert/zfxtop#7]
Works well but drive icons not showing. Didn't compile though..

**Comment by ssleert** [comment]
can u make a screenshot?

**Comment by The-Padi** [comment]
![image](https://user-images.githubusercontent.com/17253999/221506617-ea293148-ce1f-488b-aa49-51a2da243137.png)

**Comment by ssleert** [comment]
install nerd font symbols
or disable icons in config
