### ISSUE TITLE
Permission to create an AUR package?

### ISSUE THREAD

**Issue by Stetsed** [ssleert/zfxtop#8]
Good evening,

I like the project and the look of it, would you be okay with me making an AUR package for the project?

**Comment by ventureoo** [comment]
Oh, sorry, looks like I'm ahead of you x0
https://aur.archlinux.org/packages/zfxtop

Although you can still do a `-git` package.

**Comment by Stetsed** [comment]
Ah ye no worries, I'll just leave it then as the package already exists :D, great project though
